// ECharts 知识图谱 HTML — native (InAppWebView) 和 Web (iframe) 共享。
// ⚠️ 本文件由 tools/gen_graph_html_dart.py 自动生成，不要手改。
// 要修改内容请改同目录下的 graph_template.html，然后重新运行生成器。
// 生成命令: cd /Users/mac/ZZCC/zzcc && python3 tools/gen_graph_html_dart.py
//
// 占位符: __ECHARTS_BASE__ 由 Dart 侧在运行时替换为绝对 URL
// （srcdoc iframe 的 location.origin 是字符串 "null"，不能用）。

const String kGraphHtml =
    '<!DOCTYPE html>\n'
    '<html lang="zh-CN">\n'
    '<head>\n'
    '  <meta charset="UTF-8">\n'
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">\n'
    '  <title>知识图谱 3D</title>\n'
    '  <style>\n'
    '    * { margin: 0; padding: 0; box-sizing: border-box; }\n'
    '    html, body { width: 100%; height: 100%; overflow: hidden; background: #0a0a1a; }\n'
    '    #chart { width: 100%; height: 100%; }\n'
    '\n'
    '    #panel {\n'
    '      position: absolute; top: 12px; left: 12px; z-index: 10;\n'
    '      background: rgba(10, 10, 30, 0.82);\n'
    '      border: 1px solid rgba(0, 212, 255, 0.3);\n'
    '      border-radius: 10px;\n'
    '      padding: 12px 14px;\n'
    '      min-width: 200px;\n'
    '      font-family: -apple-system, \'PingFang SC\', \'Microsoft YaHei\', sans-serif;\n'
    '      color: #cce8ff;\n'
    '      font-size: 13px;\n'
    '      backdrop-filter: blur(6px);\n'
    '    }\n'
    '    #panel h3 {\n'
    '      margin: 0 0 8px 0; font-size: 14px; font-weight: 600;\n'
    '      color: #00d4ff;\n'
    '      border-bottom: 1px solid rgba(0,212,255,0.2);\n'
    '      padding-bottom: 6px;\n'
    '    }\n'
    '    #panel .stat-row {\n'
    '      display: flex; justify-content: space-between; margin: 4px 0;\n'
    '    }\n'
    '    #panel .stat-val { color: #ffffff; font-weight: 600; }\n'
    '\n'
    '    #tooltip {\n'
    '      position: absolute; z-index: 20;\n'
    '      background: rgba(10, 10, 30, 0.9);\n'
    '      border: 1px solid rgba(0,212,255,0.5);\n'
    '      border-radius: 8px;\n'
    '      padding: 10px 14px;\n'
    '      font-family: -apple-system, \'PingFang SC\', sans-serif;\n'
    '      color: #e0f0ff;\n'
    '      font-size: 13px;\n'
    '      max-width: 260px;\n'
    '      pointer-events: none;\n'
    '      display: none;\n'
    '      line-height: 1.5;\n'
    '    }\n'
    '    #tooltip .tip-title { color: #00d4ff; font-weight: 600; margin-bottom: 4px; }\n'
    '    #tooltip .tip-tag { display: inline-block; background: rgba(0,212,255,0.15); border-radius: 4px; padding: 1px 6px; margin: 2px 3px 2px 0; font-size: 11px; }\n'
    '\n'
    '    #loading {\n'
    '      position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);\n'
    '      color: #00d4ff; font-family: -apple-system, sans-serif;\n'
    '      font-size: 16px; z-index: 5; text-align: center;\n'
    '    }\n'
    '    #loading.hidden { display: none; }\n'
    '  </style>\n'
    '</head>\n'
    '<body>\n'
    '\n'
    '<div id="panel">\n'
    '  <h3>📊 图谱概览</h3>\n'
    '  <div class="stat-row"><span>节点</span><span class="stat-val" id="stat-nodes">—</span></div>\n'
    '  <div class="stat-row"><span>边</span><span class="stat-val" id="stat-links">—</span></div>\n'
    '  <div class="stat-row"><span>空间</span><span class="stat-val" id="stat-space">—</span></div>\n'
    '  <div id="legend" style="margin-top:8px;"></div>\n'
    '</div>\n'
    '\n'
    '<div id="tooltip">\n'
    '  <div class="tip-title" id="tip-title"></div>\n'
    '  <div id="tip-tag" style="margin-top:4px;"></div>\n'
    '  <div id="tip-props" style="margin-top:4px; font-size:12px; color:#9dc8e8;"></div>\n'
    '</div>\n'
    '\n'
    '<div id="loading">\n'
    '  <div id="loading-spinner">⏳ 加载中...</div>\n'
    '</div>\n'
    '\n'
    '<div id="chart"></div>\n'
    '<div id="diag-banner" style="position:fixed;top:0;right:0;z-index:99;background:#1a3a1a;color:#6bcb77;padding:6px 10px;font-size:11px;border-left:2px solid #6bcb77;max-width:60%;word-break:break-all;display:none;"></div>\n'
    '\n'
    '<script>\n'
    '(function () {\n'
    '  // 全局错误捕获：任何抛错都写进 loading 区，避免无声卡死\n'
    '  window.__diag = {\n'
    '    webglOK: false, is3D: true, chart: null, use3D: null,\n'
    '    echartsReady: false, initError: null, setOptionDone: false,\n'
    '    dataNodes: 0, dataLinks: 0, step: \'start\', errMsg: null,\n'
    '    loaded: [], failed: []\n'
    '  };\n'
    '  function showFatal(msg) {\n'
    '    window.__diag.errMsg = String(msg);\n'
    '    var el = document.getElementById(\'loading-spinner\');\n'
    '    if (el) {\n'
    '      el.textContent = String.fromCharCode(10060) + msg;\n'
    '      el.style.color = \'#ff6b6b\';\n'
    '      el.style.fontSize = \'13px\';\n'
    '      el.style.maxWidth = \'92%\';\n'
    '      el.style.lineHeight = \'1.5\';\n'
    '    }\n'
    '  }\n'
    '  function step(name) {\n'
    '    window.__diag.step = name;\n'
    '    var el = document.getElementById(\'loading-spinner\');\n'
    '    if (el && window.__diag.errMsg === null) { el.textContent = \'\' + name; }\n'
    '  }\n'
    '  window.addEventListener(\'error\', function (e) {\n'
    '    window.__diag.errMsg = window.__diag.errMsg || (\'JS错误: \' + (e.message || e));\n'
    '    showFatal(window.__diag.errMsg);\n'
    '  }, true);\n'
    '  window.addEventListener(\'unhandledrejection\', function (e) {\n'
    '    var r = e.reason && (e.reason.message || e.reason.message) || e.reason || e;\n'
    '    window.__diag.errMsg = window.__diag.errMsg || (\'Promise拒绝: \' + r);\n'
    '    showFatal(window.__diag.errMsg);\n'
    '  });\n'
    '  // postMessage 消息日志：iframe 内部直接把收到的消息写进 loading 区，\n'
    '  // 便于通过截图诊断父子通信是否打通\n'
    '  window.__msgLog = [];\n'
    '  function setBanner(t) {\n'
    '    var b = document.getElementById(\'diag-banner\');\n'
    '    if (b) { b.style.display = \'block\'; b.textContent = t; }\n'
    '  }\n'
    '  window.addEventListener(\'message\', function (e) {\n'
    '    var d = e.data;\n'
    '    var t = d && typeof d === \'object\' ? (\'[\' + (d.type || \'?\') + \']\') : \'非对象消息\';\n'
    '    window.__msgLog.push(t + \' @\' + new Date().toISOString().slice(11,19));\n'
    '  }, true);\n'
    '\n'
    '  // postMessage 通信：srcdoc iframe 的 contentWindow 被沙箱隔离，\n'
    '  // 父窗口无法通过 eval 或属性访问调用 iframe 内部函数。\n'
    '  // 必须用 postMessage + message 事件通信，且监听器要尽早注册\n'
    '  // （不能等 ECharts 加载完才注册，否则早期消息会丢）。\n'
    '  window.addEventListener(\'message\', function (e) {\n'
    '    var data = e.data;\n'
    '    // Dart 侧 postMessage 传的是 JSON 字符串（结构化克隆 Dart Map 在 JS 侧\n'
    '    // 可能不是普通对象，导致 data.nodes 读不到），统一在这里 parse 成对象。\n'
    '    if (typeof data === \'string\') {\n'
    '      try { data = JSON.parse(data); }\n'
    '      catch (err) { showFatal(\'message 不是合法 JSON: \' + err.message); return; }\n'
    '    }\n'
    '    if (window.__msgLog && data && typeof data === \'object\') {\n'
    '      window.__msgLog.push(\'收到 \' + (data.type || \'?\') + \' @\' + new Date().toISOString().slice(11,19));\n'
    '    }\n'
    '    if (typeof e.data === \'string\') setBanner(\'收到字符串消息(len=\' + e.data.length + \') 前30字: \' + e.data.slice(0,30));\n'
    '    if (data && typeof data === \'object\') setBanner(\'收到对象消息 type=\' + (data.type||\'?\') + \' nodes=\' + (data.nodes?data.nodes.length:\'无\'));\n'
    '    if (!data || typeof data !== \'object\') return;\n'
    '    if (data.type === \'update\') {\n'
    '      // 数据到了但 chart 可能还没初始化（ECharts 未加载完成），\n'
    '      // 先保证 chart 存在再渲染\n'
    '      if (!window.__diag.chart) {\n'
    '        try { initChart(); } catch (err) { showFatal(\'initChart 抛错: \' + (err && err.stack || err)); }\n'
    '      }\n'
    '      window.updateGraph(data);\n'
    '    } else if (data.type === \'toggle\') {\n'
    '      window.toggleView();\n'
    '    } else if (data.type === \'ping\') {\n'
    '      // 父窗口探活：回 ack 带完整诊断信息\n'
    '      window.parent.postMessage({\n'
    '        type: \'ack\',\n'
    '        step: window.__diag.step,\n'
    '        echartsReady: window.__diag.echartsReady,\n'
    '        chartReady: !!window.__diag.chart,\n'
    '        webglOK: window.__diag.webglOK,\n'
    '        loaded: window.__diag.loaded || [],\n'
    '        failed: window.__diag.failed || [],\n'
    '        errMsg: window.__diag.errMsg\n'
    '      }, \'*\');\n'
    '    }\n'
    '  });\n'
    '\n'
    '  // WebGL 探测：headless Chrome 无 WebGL，需走 2D 降级\n'
    '  function supportsWebGL() {\n'
    '    try {\n'
    '      var c = document.createElement(\'canvas\');\n'
    '      return !!(window.WebGLRenderingContext && (c.getContext(\'webgl\') || c.getContext(\'experimental-webgl\')));\n'
    '    } catch (e) { return false; }\n'
    '  }\n'
    '  window.__diag.webglOK = supportsWebGL();\n'
    '  var webglOK = window.__diag.webglOK;\n'
    '  step(\'1/5 WebGL探测完成, webglOK=\' + webglOK);\n'
    '\n'
    '  // base 由 Dart 侧注入占位符 __ECHARTS_BASE__（srcdoc iframe 的 location.origin\n'
    '  // 是字符串 "null"，不能用；主页面 location 正常，Dart 侧算好绝对 URL 注入）。\n'
    '  // 占位符未替换时兜底到容器本地路径，避免 ReferenceError 中断整个 IIFE。\n'
    '  var base = (typeof __ECHARTS_BASE__ !== \'undefined\' && __ECHARTS_BASE__) || \'http://127.0.0.1:8001/static/echarts\';\n'
    '  base = String(base).replace(/\\/\$/, \'\');\n'
    '  step(\'2/5 解析ECharts base=\' + base);\n'
    '\n'
    '  // 动态加载 ECharts：srcdoc iframe 没有 base URL，相对路径会解析成 about:srcdoc，\n'
    '  // 必须拼成绝对 URL。优先走容器本地，失败再降级 CDN。\n'
    '  var localScripts = [base + \'/echarts.min.js\', base + \'/echarts-gl.min.js\'];\n'
    '  var cdnScripts = [\n'
    '    \'https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js\',\n'
    '    \'https://cdn.jsdelivr.net/npm/echarts-gl@2.0.9/dist/echarts-gl.min.js\'\n'
    '  ];\n'
    '\n'
    '  // 单个脚本加载，超时兜底：避免既不 onload 也不 onerror（CDN hang）导致永久挂起\n'
    '  function loadScript(url, timeoutMs) {\n'
    '    return new Promise(function (resolve) {\n'
    '      var done = false;\n'
    '      var s = document.createElement(\'script\');\n'
    '      var timer = setTimeout(function () {\n'
    '        if (done) return;\n'
    '        done = true;\n'
    '        window.__diag.failed.push(url + \' (超时\' + timeoutMs + \'ms)\');\n'
    '        step(\'3/5 超时: \' + url);\n'
    '        resolve(false);\n'
    '      }, timeoutMs);\n'
    '      s.onload = function () {\n'
    '        if (done) return;\n'
    '        done = true;\n'
    '        clearTimeout(timer);\n'
    '        window.__diag.loaded.push(url);\n'
    '        resolve(true);\n'
    '      };\n'
    '      s.onerror = function () {\n'
    '        if (done) return;\n'
    '        done = true;\n'
    '        clearTimeout(timer);\n'
    '        window.__diag.failed.push(url);\n'
    '        resolve(false);\n'
    '      };\n'
    '      s.src = url;\n'
    '      document.head.appendChild(s);\n'
    '    });\n'
    '  }\n'
    '\n'
    '  // 顺序加载一组脚本（允许失败继续）\n'
    '  function loadAll(list) {\n'
    '    var chain = Promise.resolve();\n'
    '    list.forEach(function (u) {\n'
    '      chain = chain.then(function () {\n'
    '        step(\'3/5 加载中[\' + list.indexOf(u) + \'/\' + list.length + \']: \' + u);\n'
    '        return loadScript(u, 12000);\n'
    '      });\n'
    '    });\n'
    '    return chain;\n'
    '  }\n'
    '\n'
    '  // 总体超时兜底：任何情况下都会收敛到 boot()，loading 区一定能更新\n'
    '  setTimeout(function () {\n'
    '    if (window.__diag.errMsg === null && !window.__diag.chart) {\n'
    '      showFatal(\'ECharts 加载超时, echarts类型=\' + (typeof echarts) +\n'
    '        \' loaded=\' + JSON.stringify(window.__diag.loaded) +\n'
    '        \' failed=\' + JSON.stringify(window.__diag.failed));\n'
    '    }\n'
    '  }, 25000);\n'
    '\n'
    '  (function bootWhenReady() {\n'
    '    if (typeof echarts === \'undefined\') {\n'
    '      step(\'3/5 开始加载本地脚本, scripts=\' + localScripts.length + \'/\' + cdnScripts.length);\n'
    '      return loadAll(localScripts).then(function () {\n'
    '        if (typeof echarts !== \'undefined\') {\n'
    '          step(\'3/5 本地脚本就绪, echarts=\' + typeof echarts);\n'
    '          boot();\n'
    '          return;\n'
    '        }\n'
    '        step(\'3/5 本地失败，回退 CDN, failed=\' + JSON.stringify(window.__diag.failed));\n'
    '        return loadAll(cdnScripts).then(function () {\n'
    '          step(\'3/5 CDN链完成, echarts=\' + typeof echarts);\n'
    '          boot();\n'
    '        });\n'
    '      });\n'
    '    }\n'
    '    boot();\n'
    '  })();\n'
    '\n'
    '  var chart = null;\n'
    '  var is3D = true;\n'
    '  var currentSpace = \'\';\n'
    '  var rawData = { nodes: [], links: [], categories: [] };\n'
    '  var _bootDone = false;\n'
    '\n'
    '  function boot() {\n'
    '    if (_bootDone) return;\n'
    '    _bootDone = true;\n'
    '    window.__diag.echartsReady = (typeof echarts !== \'undefined\');\n'
    '    step(\'4/5 ECharts已加载, echartsReady=\' + window.__diag.echartsReady);\n'
    '    if (typeof echarts === \'undefined\') {\n'
    '      showFatal(\'ECharts 库加载失败, loaded=\' + JSON.stringify(window.__diag.loaded) +\n'
    '        \' failed=\' + JSON.stringify(window.__diag.failed));\n'
    '      return;\n'
    '    }\n'
    '    window.addEventListener(\'message\', function (e) { onMessage(e.data); });\n'
    '    // 直接调用 initChart（不用 rAF：iframe/headless 环境 rAF 可能不触发）\n'
    '    try {\n'
    '      initChart();\n'
    '    } catch (err) {\n'
    '      showFatal(\'initChart 抛错: \' + (err && err.stack || err));\n'
    '    }\n'
    '  }\n'
    '\n'
    '  var __initTries = 0;\n'
    '  function initChart() {\n'
    '    var dom = document.getElementById(\'chart\');\n'
    '    if (!dom || dom.offsetWidth === 0 || dom.offsetHeight === 0) {\n'
    '      __initTries++;\n'
    '      step(\'4/5 等待#chart布局, offset=\' +\n'
    '        (dom ? dom.offsetWidth + \'x\' + dom.offsetHeight : \'null\') +\n'
    '        \' try=\' + __initTries);\n'
    '      if (__initTries > 90) {\n'
    '        showFatal(\'图表容器无尺寸, 已重试90次 (\' +\n'
    '          (dom ? dom.offsetWidth : \'?\') + \'x\' + (dom ? dom.offsetHeight : \'?\') + \' )\');\n'
    '        return;\n'
    '      }\n'
    '      setTimeout(initChart, 100);\n'
    '      return;\n'
    '    }\n'
    '    step(\'5/5 初始化图表, #chart=\' + dom.offsetWidth + \'x\' + dom.offsetHeight);\n'
    '    try {\n'
    '      chart = echarts.init(dom);\n'
    '      window.__diag.chart = chart;\n'
    '      chart.setOption({\n'
    '        backgroundColor: \'#0a0a1a\',\n'
    '        animation: false,\n'
    '        series: [{\n'
    '          type: \'graph\',\n'
    '          name: \'knowledge_graph\',\n'
    '          data: [],\n'
    '          links: []\n'
    '        }]\n'
    '      });\n'
    '      step(\'5/5 图表初始化完成, 等待数据\');\n'
    '    } catch (err) {\n'
    '      showFatal(\'initChart 内部抛错: \' + (err && err.stack || err));\n'
    '    }\n'
    '  }\n'
    '\n'
    '  function buildOption(nodes, links, categories) {\n'
    '    if (!chart) return;\n'
    '    var catNames = categories || [];\n'
    '    var catColors = [\'#00d4ff\', \'#ff6b6b\', \'#ffd93d\', \'#6bcb77\', \'#c77dff\', \'#ff9a3c\', \'#4cc9f0\', \'#f72585\'];\n'
    '    var use3D = is3D && webglOK;\n'
    '    window.__diag.use3D = use3D;\n'
    '\n'
    '    // 2D 模式：ECharts force 布局在 headless 下动画不执行，需手动算圆环坐标\n'
    '    if (!use3D) {\n'
    '      var cx = 532, cy = 500, r = 220;\n'
    '      nodes.forEach(function (n, i) {\n'
    '        var angle = (2 * Math.PI * i) / Math.max(nodes.length, 1) - Math.PI / 2;\n'
    '        n.x = cx + r * Math.cos(angle);\n'
    '        n.y = cy + r * Math.sin(angle);\n'
    '      });\n'
    '    }\n'
    '\n'
    '    var opt = {\n'
    '      animation: false,\n'
    '      backgroundColor: \'#0a0a1a\',\n'
    '      tooltip: {\n'
    '        trigger: \'item\',\n'
    '        backgroundColor: \'transparent\',\n'
    '        borderWidth: 0,\n'
    '        padding: 0,\n'
    '        textStyle: { color: \'transparent\' },\n'
    '        formatter: function (params) {\n'
    '          if (params.dataType === \'node\') {\n'
    '            var d = params.data;\n'
    '            document.getElementById(\'tip-title\').textContent = d.label || d.id;\n'
    '            var tagHtml = (d.tags || []).map(function (t) {\n'
    '              return \'<span class="tip-tag">\' + t + \'</span>\';\n'
    '            }).join(\'\');\n'
    '            document.getElementById(\'tip-tag\').innerHTML = tagHtml;\n'
    '            var propsHtml = Object.keys(d.props || {}).slice(0, 4).map(function (k) {\n'
    '              return k + \': \' + (d.props[k] || \'\');\n'
    '            }).join(\'<br>\');\n'
    '            document.getElementById(\'tip-props\').innerHTML = propsHtml;\n'
    '            document.getElementById(\'tooltip\').style.display = \'block\';\n'
    '          }\n'
    '          return \'\';\n'
    '        }\n'
    '      },\n'
    '      series: [{\n'
    '        name: \'knowledge_graph\',\n'
    '        type: use3D ? \'graphGL\' : \'graph\',\n'
    '        coordinateSystem: use3D ? \'cartesian3D\' : undefined,\n'
    '        layout: \'none\',\n'
    '        symbolSize: 30,\n'
    '        roam: true,\n'
    '        focusNodeAdjacency: true,\n'
    '        lineStyle: { width: 1.2, color: \'rgba(0,212,255,0.55)\', curveness: 0.2, opacity: 0.7 },\n'
    '        itemStyle: {\n'
    '          borderWidth: 2,\n'
    '          borderColor: \'#fff\',\n'
    '          shadowBlur: use3D ? 12 : 0,\n'
    '          shadowColor: use3D ? \'rgba(0,212,255,0.4)\' : \'transparent\'\n'
    '        },\n'
    '        label: {\n'
    '          show: true,\n'
    '          formatter: \'{b}\',\n'
    '          fontSize: 12,\n'
    '          color: \'#fff\',\n'
    '          fontFamily: \'-apple system, PingFang SC, sans-serif\',\n'
    '          textShadowColor: use3D ? \'#000\' : \'transparent\',\n'
    '          textShadowBlur: use3D ? 4 : 0\n'
    '        },\n'
    '        emphasis: {\n'
    '          lineStyle: { width: 2.5, color: \'#00d4ff\', curveness: 0.1 },\n'
    '          itemStyle: { shadowBlur: use3D ? 20 : 0, shadowColor: use3D ? \'#00d4ff\' : \'transparent\' }\n'
    '        },\n'
    '        categories: catNames.map(function (c, i) {\n'
    '          return { name: c, itemStyle: { color: catColors[i % catColors.length] } };\n'
    '        }),\n'
    '        data: nodes.map(function (n) {\n'
    '          return Object.assign({\n'
    '            id: n.id,\n'
    '            name: n.id,\n'
    '            label: n.label || n.id,\n'
    '            x: n.x,\n'
    '            y: n.y,\n'
    '            symbolSize: n.symbolSize || 20,\n'
    '            category: n.category || 0,\n'
    '            tags: n.tags || [],\n'
    '            props: n.props || {},\n'
    '            itemStyle: { color: catColors[(n.category || 0) % catColors.length] }\n'
    '          }, use3D ? { value: [n.x || 0, n.y || 0, n.z || 0] } : {});\n'
    '        }),\n'
    '        links: links.map(function (l) {\n'
    '          return { source: l.source, target: l.target, name: l.label || \'\' };\n'
    '        })\n'
    '      }]\n'
    '    };\n'
    '\n'
    '    // 2D 模式不能带 graphGL 专用字段，否则 ECharts 会报错\n'
    '    if (use3D) {\n'
    '      opt.series[0].nodeScaleRatio = 0.8;\n'
    '      opt.xAxis3D = { show: false, min: -100, max: 100 };\n'
    '      opt.yAxis3D = { show: false, min: -100, max: 100 };\n'
    '      opt.zAxis3D = { show: false, min: -100, max: 100 };\n'
    '      opt.grid3D = {\n'
    '        show: false, width: \'100%\', height: \'100%\',\n'
    '        viewControl: {\n'
    '          beta: 40, alpha: 30, rotateSpeed: 30,\n'
    '          zoomSensitivity: 1.2, autoRotate: true,\n'
    '          autoRotateAfterInitialAnimationDelay: 2000\n'
    '        }\n'
    '      };\n'
    '    }\n'
    '\n'
    '    chart.setOption(opt, { notMerge: true });\n'
    '    window.__diag.setOptionDone = true;\n'
    '    step(\'5/5 渲染完成, nodes=\' + nodes.length + \' links=\' + links.length + \' use3D=\' + use3D);\n'
    '  }\n'
    '\n'
    '  function updateStats(nodes, links, space) {\n'
    '    document.getElementById(\'stat-nodes\').textContent = nodes.length;\n'
    '    document.getElementById(\'stat-links\').textContent = links.length;\n'
    '    document.getElementById(\'stat-space\').textContent = space || \'—\';\n'
    '  }\n'
    '\n'
    '  // tooltip 跟随鼠标\n'
    '  document.addEventListener(\'mousemove\', function (e) {\n'
    '    var tip = document.getElementById(\'tooltip\');\n'
    '    if (tip.style.display === \'block\') {\n'
    '      tip.style.left = (e.clientX + 14) + \'px\';\n'
    '      tip.style.top = (e.clientY - 10) + \'px\';\n'
    '    }\n'
    '  });\n'
    '  document.addEventListener(\'click\', function () {\n'
    '    document.getElementById(\'tooltip\').style.display = \'none\';\n'
    '  });\n'
    '\n'
    '  // 父窗口调用入口：更新图谱数据\n'
    '  window.updateGraph = function (data) {\n'
    '    window.__diag.dataNodes = data.nodes.length;\n'
    '    window.__diag.dataLinks = data.links.length;\n'
    '    var nodes = data.nodes || [];\n'
    '    var links = data.links || [];\n'
    '    var categories = data.categories || [];\n'
    '    var space = data.space || \'\';\n'
    '\n'
    '    if (nodes.length === 0) {\n'
    '      document.getElementById(\'loading-spinner\').textContent = \'⚠️ 暂无图谱数据\';\n'
    '      return;\n'
    '    }\n'
    '    document.getElementById(\'loading\').classList.add(\'hidden\');\n'
    '    rawData = { nodes: nodes, links: links, categories: categories };\n'
    '    currentSpace = space;\n'
    '    buildOption(nodes, links, categories);\n'
    '    updateStats(nodes, links, space);\n'
    '  };\n'
    '\n'
    '  // 3D / 2D 切换\n'
    '  window.toggleView = function () {\n'
    '    if (!chart || !webglOK || !rawData.nodes.length) return;\n'
    '    is3D = !is3D;\n'
    '    buildOption(rawData.nodes, rawData.links, rawData.categories);\n'
    '  };\n'
    '\n'
    '  window.addEventListener(\'resize\', function () { if (chart) chart.resize(); });\n'
    '\n'
    '  function onMessage(data) {\n'
    '    // 已迁移到顶层 addEventListener(\'message\', ...)，这里保留兼容旧调用\n'
    '    if (data && data.type === \'update\') {\n'
    '      window.updateGraph(data);\n'
    '    }\n'
    '  }\n'
    '})();\n'
    '</script>\n'
    '</body>\n'
    '</html>';
