// ECharts 知识图谱 HTML — native (InAppWebView) 和 Web (iframe) 共享
const String kGraphHtml = '<!DOCTYPE html>\n'
    '<html lang="zh-CN">\n'
    '<head>\n'
    '  <meta charset="UTF-8">\n'
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">\n'
    '  <title>知识图谱 3D</title>\n'
    '  <style>\n'
    '    * { margin: 0; padding: 0; box-sizing: border-box; }\n'
    '    html, body { width: 100%; height: 100%; overflow: hidden; background: #0a0a1a; }\n'
    '    #chart { width: 100%; height: 100%; }\n'
    '\n'
    '    #panel {\n'
    '      position: absolute; top: 12px; left: 12px; z-index: 10;\n'
    '      background: rgba(10, 10, 30, 0.82);\n'
    '      border: 1px solid rgba(0, 212, 255, 0.3);\n'
    '      border-radius: 10px;\n'
    '      padding: 12px 14px;\n'
    '      min-width: 200px;\n'
    '      font-family: -apple-system, \'PingFang SC\', \'Microsoft YaHei\', sans-serif;\n'
    '      color: #cce8ff;\n'
    '      font-size: 13px;\n'
    '      backdrop-filter: blur(6px);\n'
    '    }\n'
    '    #panel h3 {\n'
    '      margin: 0 0 8px 0; font-size: 14px; font-weight: 600;\n'
    '      color: #00d4ff;\n'
    '      border-bottom: 1px solid rgba(0,212,255,0.2);\n'
    '      padding-bottom: 6px;\n'
    '    }\n'
    '    #panel .stat-row {\n'
    '      display: flex; justify-content: space-between; margin: 4px 0;\n'
    '    }\n'
    '    #panel .stat-val { color: #ffffff; font-weight: 600; }\n'
    '\n'
    '    #tooltip {\n'
    '      position: absolute; z-index: 20;\n'
    '      background: rgba(10, 10, 30, 0.9);\n'
    '      border: 1px solid rgba(0,212,255,0.5);\n'
    '      border-radius: 8px;\n'
    '      padding: 10px 14px;\n'
    '      font-family: -apple-system, \'PingFang SC\', sans-serif;\n'
    '      color: #e0f0ff;\n'
    '      font-size: 13px;\n'
    '      max-width: 260px;\n'
    '      pointer-events: none;\n'
    '      display: none;\n'
    '      line-height: 1.5;\n'
    '    }\n'
    '    #tooltip .tip-title { color: #00d4ff; font-weight: 600; margin-bottom: 4px; }\n'
    '    #tooltip .tip-tag { display: inline-block; background: rgba(0,212,255,0.15); border-radius: 4px; padding: 1px 6px; margin: 2px 3px 2px 0; font-size: 11px; }\n'
    '\n'
    '    #loading {\n'
    '      position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);\n'
    '      color: #00d4ff; font-family: -apple-system, sans-serif;\n'
    '      font-size: 16px; z-index: 5; text-align: center;\n'
    '    }\n'
    '    #loading.hidden { display: none; }\n'
    '  </style>\n'
    '</head>\n'
    '<body>\n'
    '\n'
    '<div id="panel">\n'
    '  <h3>📊 图谱概览</h3>\n'
    '  <div class="stat-row"><span>节点</span><span class="stat-val" id="stat-nodes">—</span></div>\n'
    '  <div class="stat-row"><span>边</span><span class="stat-val" id="stat-links">—</span></div>\n'
    '  <div class="stat-row"><span>空间</span><span class="stat-val" id="stat-space">—</span></div>\n'
    '  <div id="legend" style="margin-top:8px;"></div>\n'
    '</div>\n'
    '\n'
    '<div id="tooltip">\n'
    '  <div class="tip-title" id="tip-title"></div>\n'
    '  <div id="tip-tag" style="margin-top:4px;"></div>\n'
    '  <div id="tip-props" style="margin-top:4px; font-size:12px; color:#9dc8e8;"></div>\n'
    '</div>\n'
    '\n'
    '<div id="loading">\n'
    '  <div id="loading-spinner">⏳ 加载中...</div>\n'
    '</div>\n'
    '\n'
    '<div id="chart"></div>\n'
    '\n'
    '<script src="https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js"></script>\n'
    '<script src="https://cdn.jsdelivr.net/npm/echarts-gl@2.0.9/dist/echarts-gl.min.js"></script>\n'
    '<script>\n'
    '(function () {\n'
    '  var chart = null;\n'
    '  var is3D = true;\n'
    '  var currentSpace = \'\';\n'
    '  var rawData = { nodes: [], links: [], categories: [] };\n'
    '  function supportsWebGL() {\n'
    '    try {\n'
    '      var c = document.createElement(\'canvas\');\n'
    '      return !!(window.WebGLRenderingContext && (c.getContext(\'webgl\') || c.getContext(\'experimental-webgl\')));\n'
    '    } catch (e) { return false; }\n'
    '  }\n'
    '  var webglOK = supportsWebGL();\n'
    '  window.__diag = { webglOK: webglOK, is3D: is3D, chart: null, use3D: null };\n'
    '\n'
    '  function initChart() {\n'
    '    var dom = document.getElementById(\'chart\');\n'
    '    if (!dom || dom.offsetWidth === 0 || dom.offsetHeight === 0) {\n'
    '      requestAnimationFrame(initChart);\n'
    '      return;\n'
    '    }\n'
    '    chart = echarts.init(dom);\n'
    '    window.__diag.chart = chart;\n'
    '    var option = {\n'
    '      backgroundColor: \'#0a0a1a\',\n'
    '      animation: true,\n'
    '      animationDurationUpdate: 800,\n'
    '      progressive: 400,\n'
    '      tooltip: {\n'
    '        trigger: \'item\',\n'
    '        backgroundColor: \'transparent\',\n'
    '        borderWidth: 0,\n'
    '        padding: 0,\n'
    '        textStyle: { color: \'transparent\' },\n'
    '        formatter: function (params) {\n'
    '          if (params.dataType === \'node\') {\n'
    '            var d = params.data;\n'
    '            document.getElementById(\'tip-title\').textContent = d.label || d.id;\n'
    '            var tagHtml = (d.tags || []).map(function (t) {\n'
    '              return \'<span class="tip-tag">\' + t + \'</span>\';\n'
    '            }).join(\'\');\n'
    '            document.getElementById(\'tip-tag\').innerHTML = tagHtml;\n'
    '            var propsHtml = Object.keys(d.props || {}).slice(0, 4).map(function (k) {\n'
    '              return k + \': \' + (d.props[k] || \'\');\n'
    '            }).join(\'<br>\');\n'
    '            document.getElementById(\'tip-props\').innerHTML = propsHtml;\n'
    '            var tipEl = document.getElementById(\'tooltip\');\n'
    '            tipEl.style.display = \'block\';\n'
    '            return \'\';\n'
    '          }\n'
    '          return \'\';\n'
    '        }\n'
    '      }\n'
    '    };\n'
    '    if (webglOK) {\n'
    '      option.xAxis3D = { show: false, min: -100, max: 100 };\n'
    '      option.yAxis3D = { show: false, min: -100, max: 100 };\n'
    '      option.zAxis3D = { show: false, min: -100, max: 100 };\n'
    '      option.grid3D = { show: false, width: \'100%\', height: \'100%\', viewControl: { beta: 40, alpha: 30, rotateSpeed: 30, zoomSensitivity: 1.2, autoRotate: true, autoRotateAfterInitialAnimationDelay: 2000 } };\n'
    '      option.series = [{\n'
    '        type: \'graphGL\',\n'
    '        name: \'knowledge_graph\',\n'
    '        coordinateSystem: \'cartesian3D\',\n'
    '        symbolSize: 30,\n'
    '        nodeScaleRatio: 0.8,\n'
    '        roam: true,\n'
    '        focusNodeAdjacency: true,\n'
    '        lineStyle: { width: 1.2, color: \'rgba(0,212,255,0.55)\', curveness: 0.2, opacity: 0.7 },\n'
    '        itemStyle: { borderWidth: 2, borderColor: \'#fff\', shadowBlur: 12, shadowColor: \'rgba(0,212,255,0.4)\' },\n'
    '        label: { show: true, formatter: \'{b}\', fontSize: 12, color: \'#fff\', fontFamily: \'-apple-system, PingFang SC, sans-serif\', textShadowColor: \'#000\', textShadowBlur: 4 },\n'
    '        emphasis: { lineStyle: { width: 2.5, color: \'#00d4ff\', curveness: 0.1 }, itemStyle: { shadowBlur: 20, shadowColor: \'#00d4ff\' } },\n'
    '        categories: [],\n'
    '        data: [],\n'
    '        links: [],\n'
    '        force: { repulsion: 120, gravity: 0.05, edgeLength: [50, 200], layoutAnimation: true, initLayout: \'circular\' }\n'
    '      }];\n'
    '    } else {\n'
    '      option.series = [{\n'
    '        type: \'graph\',\n'
    '        name: \'knowledge_graph\',\n'
    '        layout: \'force\',\n'
    '        symbolSize: 30,\n'
    '        roam: true,\n'
    '        focusNodeAdjacency: true,\n'
    '        force: { repulsion: 120, gravity: 0.05, edgeLength: [50, 200], layoutAnimation: true },\n'
    '        lineStyle: { width: 1.2, color: \'rgba(0,212,255,0.55)\', curveness: 0.2, opacity: 0.7 },\n'
    '        itemStyle: { borderWidth: 2, borderColor: \'#fff\' },\n'
    '        label: { show: true, formatter: \'{b}\', fontSize: 12, color: \'#fff\', fontFamily: \'-apple-system, PingFang SC, sans-serif\' },\n'
    '        emphasis: { lineStyle: { width: 2.5, color: \'#00d4ff\', curveness: 0.1 } },\n'
    '        categories: [],\n'
    '        data: [],\n'
    '        links: []\n'
    '      }];\n'
    '    }\n'
    '    chart.setOption(option);\n'
    '  }\n'
    '\n'
    '  // Follow mouse for tooltip\n'
    '  document.addEventListener(\'mousemove\', function (e) {\n'
    '    var tip = document.getElementById(\'tooltip\');\n'
    '    if (tip.style.display === \'block\') {\n'
    '      tip.style.left = (e.clientX + 14) + \'px\';\n'
    '      tip.style.top = (e.clientY - 10) + \'px\';\n'
    '    }\n'
    '  });\n'
    '  document.addEventListener(\'click\', function () {\n'
    '    document.getElementById(\'tooltip\').style.display = \'none\';\n'
    '  });\n'
    '  function buildOption(nodes, links, categories) {\n'
    '    var catNames = categories || [];\n'
    '    var catColors = [\'#00d4ff\', \'#ff6b6b\', \'#ffd93d\', \'#6bcb77\', \'#c77dff\', \'#ff9a3c\', \'#4cc9f0\', \'#f72585\'];\n'
    '    if (!chart) return;\n'
    '    var use3D = is3D && webglOK;\n'
    '    if (!use3D) {\n'
    '      var cx = 532, cy = 500, r = 220;\n'
    '      nodes.forEach(function (n, i) {\n'
    '        var angle = (2 * Math.PI * i) / Math.max(nodes.length, 1) - Math.PI / 2;\n'
    '        n.x = cx + r * Math.cos(angle);\n'
    '        n.y = cy + r * Math.sin(angle);\n'
    '      });\n'
    '    }\n'
    '    window.__diag.use3D = use3D;\n'
    '    var opt = {\n'
    '      animation: false,\n'
    '      backgroundColor: \'#0a0a1a\',\n'
    '      tooltip: {\n'
    '        trigger: \'item\',\n'
    '        backgroundColor: \'transparent\',\n'
    '        borderWidth: 0,\n'
    '        padding: 0,\n'
    '        textStyle: { color: \'transparent\' },\n'
    '        formatter: function (params) {\n'
    '          if (params.dataType === \'node\') {\n'
    '            var d = params.data;\n'
    '            document.getElementById(\'tip-title\').textContent = d.label || d.id;\n'
    '            var tagHtml = (d.tags || []).map(function (t) {\n'
    '              return \'<span class="tip-tag">\' + t + \'</span>\';\n'
    '            }).join(\'\');\n'
    '            document.getElementById(\'tip-tag\').innerHTML = tagHtml;\n'
    '            var propsHtml = Object.keys(d.props || {}).slice(0, 4).map(function (k) {\n'
    '              return k + \': \' + (d.props[k] || \'\');\n'
    '            }).join(\'<br>\');\n'
    '            document.getElementById(\'tip-props\').innerHTML = propsHtml;\n'
    '            var tipEl = document.getElementById(\'tooltip\');\n'
    '            tipEl.style.display = \'block\';\n'
    '            return \'\';\n'
    '          }\n'
    '          return \'\';\n'
    '        }\n'
    '      },\n'
    '      series: [Object.assign({\n'
    '        name: \'knowledge_graph\',\n'
    '        type: use3D ? \'graphGL\' : \'graph\',\n'
    '        coordinateSystem: use3D ? \'cartesian3D\' : undefined,\n'
    '        layout: use3D ? \'none\' : \'none\',\n'
    '        force: undefined,\n'
    '        symbolSize: 30,\n'

    '        roam: true,\n'
    '        focusNodeAdjacency: true,\n'
    '        lineStyle: { width: 1.2, color: \'rgba(0,212,255,0.55)\', curveness: 0.2, opacity: 0.7 },\n'
    '        itemStyle: { borderWidth: 2, borderColor: \'#fff\', shadowBlur: use3D ? 12 : 0, shadowColor: use3D ? \'rgba(0,212,255,0.4)\' : \'transparent\' },\n'
    '        label: { show: true, formatter: \'{b}\', fontSize: 12, color: \'#fff\', fontFamily: \'-apple-system, PingFang SC, sans-serif\', textShadowColor: use3D ? \'#000\' : \'transparent\', textShadowBlur: use3D ? 4 : 0 },\n'
    '        emphasis: { lineStyle: { width: 2.5, color: \'#00d4ff\', curveness: 0.1 }, itemStyle: { shadowBlur: use3D ? 20 : 0, shadowColor: use3D ? \'#00d4ff\' : \'transparent\' } },\n'
    '        categories: catNames.map(function (c, i) {\n'
    '          return { name: c, itemStyle: { color: catColors[i % catColors.length] } };\n'
    '        }),\n'
    '        data: nodes.map(function (n) {\n'
    '          return Object.assign({\n'
    '            id: n.id,\n'
    '            name: n.id,\n'
    '            label: n.label || n.id,\n'
    '            x: n.x,\n'
    '            y: n.y,\n'
    '            symbolSize: n.symbolSize || 20,\n'
    '            category: n.category || 0,\n'
    '            tags: n.tags || [],\n'
    '            props: n.props || {},\n'
    '            itemStyle: { color: catColors[(n.category || 0) % catColors.length] }\n'
    '          }, use3D ? { value: [n.x || 0, n.y || 0, n.z || 0] } : {});\n'
    '        }),\n'
    '        links: links.map(function (l) {\n'
    '          return { source: l.source, target: l.target, name: l.label || \'\' };\n'
    '        })\n'
    '      }, use3D ? { nodeScaleRatio: 0.8 } : {})]\n'
    '    };\n'
    '    if (use3D) {\n'
    '      opt.xAxis3D = { show: false, min: -100, max: 100 };\n'
    '      opt.yAxis3D = { show: false, min: -100, max: 100 };\n'
    '      opt.zAxis3D = { show: false, min: -100, max: 100 };\n'
    '      opt.grid3D = { show: false, width: \'100%\', height: \'100%\', viewControl: { beta: 40, alpha: 30, rotateSpeed: 30, zoomSensitivity: 1.2, autoRotate: true, autoRotateAfterInitialAnimationDelay: 2000 } };\n'
    '    }\n'
    '    chart.setOption(opt, { notMerge: true });\n'
    '    window.__diag.setOptionDone = true;\n'
    '  }\n'
    '\n'
    '  function updateStats(nodes, links, space) {\n'
    '    document.getElementById(\'stat-nodes\').textContent = nodes.length;\n'
    '    document.getElementById(\'stat-links\').textContent = links.length;\n'
    '    document.getElementById(\'stat-space\').textContent = space || \'—\';\n'
    '  }\n'
    '\n'
    '  window.updateGraph = function (data) {\n'
    '    window.__diag.dataNodes = data.nodes.length;\n'
    '    window.__diag.dataLinks = data.links.length;\n'
    '    var nodes = data.nodes || [];\n'
    '    var links = data.links || [];\n'
    '    var categories = data.categories || [];\n'
    '    var space = data.space || \'\';\n'
    '\n'
    '    if (nodes.length === 0) {\n'
    '      document.getElementById(\'loading-spinner\').textContent = \'⚠️ 暂无图谱数据\';\n'
    '      return;\n'
    '    }\n'
    '\n'
    '    document.getElementById(\'loading\').classList.add(\'hidden\');\n'
    '    rawData = { nodes: nodes, links: links, categories: categories };\n'
    '    currentSpace = space;\n'
    '\n'
    '    buildOption(nodes, links, categories);\n'
    '    updateStats(nodes, links, space);\n'
    '  };\n'
    '\n'
    '  window.addEventListener(\'resize\', function () { if (chart) chart.resize(); });\n'
    '\n'
    '  // 3D / 2D 切换\n'
    '  window.toggleView = function () {\n'
    '    if (!chart) return;\n'
    '    if (!webglOK) return;\n'
    '    is3D = !is3D;\n'
    '    if (is3D) {\n'
    '      chart.setOption({\n'
    '        grid3D: { show: false, viewControl: { beta: 40, alpha: 30, rotateSpeed: 30, zoomSensitivity: 1.2, autoRotate: true, autoRotateAfterInitialAnimationDelay: 2000 } }\n'
    '      });\n'
    '    } else {\n'
    '      chart.setOption({\n'
    '        grid3D: { show: false, viewControl: { projection: \'orthographic\', beta: 0, alpha: 0, rotateSpeed: 0, zoomSensitivity: 0.8 } }\n'
    '      });\n'
    '    }\n'
    '  };\n'
    '\n'
    '  initChart();\n'
    '})();\n'
    '</script>\n'
    '</body>\n'
    '</html>\n';
