// Mocks generated by Mockito 5.4.4 from annotations
// in zzcc/test/integration/auth_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:zzcc/core/services/config_service.dart' as _i2;
import 'package:zzcc/data/models/chat_message.dart' as _i7;
import 'package:zzcc/data/models/chat_room.dart' as _i3;
import 'package:zzcc/data/models/chat_user.dart' as _i6;
import 'package:zzcc/data/sources/chat_remote_source.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConfigService_0 extends _i1.SmartFake implements _i2.ConfigService {
  _FakeConfigService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatRoom_1 extends _i1.SmartFake implements _i3.ChatRoom {
  _FakeChatRoom_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncResponse_2 extends _i1.SmartFake implements _i4.SyncResponse {
  _FakeSyncResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteSource extends _i1.Mock implements _i4.ChatRemoteSource {
  MockChatRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConfigService get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeConfigService_0(
          this,
          Invocation.getter(#config),
        ),
      ) as _i2.ConfigService);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  void setAccessToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAccessToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i6.ChatUser?> register({
    required String? username,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #username: username,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i5.Future<_i6.ChatUser?>.value(),
      ) as _i5.Future<_i6.ChatUser?>);

  @override
  _i5.Future<_i6.ChatUser?> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i6.ChatUser?>.value(),
      ) as _i5.Future<_i6.ChatUser?>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.ChatUser?> syncAccount({
    required String? localUid,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAccount,
          [],
          {
            #localUid: localUid,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i5.Future<_i6.ChatUser?>.value(),
      ) as _i5.Future<_i6.ChatUser?>);

  @override
  _i5.Future<Map<String, dynamic>> getProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [userId],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> setDisplayName(String? displayName) => (super.noSuchMethod(
        Invocation.method(
          #setDisplayName,
          [displayName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ChatRoom>> getRooms() => (super.noSuchMethod(
        Invocation.method(
          #getRooms,
          [],
        ),
        returnValue: _i5.Future<List<_i3.ChatRoom>>.value(<_i3.ChatRoom>[]),
      ) as _i5.Future<List<_i3.ChatRoom>>);

  @override
  _i5.Future<_i3.ChatRoom> createRoom({
    String? name,
    String? topic,
    List<String>? invite,
    bool? isDirect = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoom,
          [],
          {
            #name: name,
            #topic: topic,
            #invite: invite,
            #isDirect: isDirect,
          },
        ),
        returnValue: _i5.Future<_i3.ChatRoom>.value(_FakeChatRoom_1(
          this,
          Invocation.method(
            #createRoom,
            [],
            {
              #name: name,
              #topic: topic,
              #invite: invite,
              #isDirect: isDirect,
            },
          ),
        )),
      ) as _i5.Future<_i3.ChatRoom>);

  @override
  _i5.Future<_i3.ChatRoom> joinRoom(String? roomIdOrAlias) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinRoom,
          [roomIdOrAlias],
        ),
        returnValue: _i5.Future<_i3.ChatRoom>.value(_FakeChatRoom_1(
          this,
          Invocation.method(
            #joinRoom,
            [roomIdOrAlias],
          ),
        )),
      ) as _i5.Future<_i3.ChatRoom>);

  @override
  _i5.Future<void> leaveRoom(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #leaveRoom,
          [roomId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.ChatMessage>> getMessages(
    String? roomId, {
    int? limit = 50,
    String? fromToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [roomId],
          {
            #limit: limit,
            #fromToken: fromToken,
          },
        ),
        returnValue:
            _i5.Future<List<_i7.ChatMessage>>.value(<_i7.ChatMessage>[]),
      ) as _i5.Future<List<_i7.ChatMessage>>);

  @override
  _i5.Future<String> sendMessage(
    String? roomId,
    String? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            roomId,
            body,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #sendMessage,
            [
              roomId,
              body,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i4.SyncResponse> sync({
    String? since,
    int? timeout = 30000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sync,
          [],
          {
            #since: since,
            #timeout: timeout,
          },
        ),
        returnValue: _i5.Future<_i4.SyncResponse>.value(_FakeSyncResponse_2(
          this,
          Invocation.method(
            #sync,
            [],
            {
              #since: since,
              #timeout: timeout,
            },
          ),
        )),
      ) as _i5.Future<_i4.SyncResponse>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i2.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  bool get keepLoggedIn => (super.noSuchMethod(
        Invocation.getter(#keepLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  String get nebulaApiBaseUrl => (super.noSuchMethod(
        Invocation.getter(#nebulaApiBaseUrl),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#nebulaApiBaseUrl),
        ),
      ) as String);

  @override
  String get nebulaApiKey => (super.noSuchMethod(
        Invocation.getter(#nebulaApiKey),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#nebulaApiKey),
        ),
      ) as String);

  @override
  String get appDataPath => (super.noSuchMethod(
        Invocation.getter(#appDataPath),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#appDataPath),
        ),
      ) as String);

  @override
  bool get enableSplashAnimation => (super.noSuchMethod(
        Invocation.getter(#enableSplashAnimation),
        returnValue: false,
      ) as bool);


  @override
  String? get chatAccessToken => (super.noSuchMethod(
        Invocation.getter(#chatAccessToken),
        returnValue: _i8.dummyValue<String?>(
          this,
          Invocation.getter(#chatAccessToken),
        ),
      ) as String?);

  @override
  String? get chatUserId => (super.noSuchMethod(
        Invocation.getter(#chatUserId),
        returnValue: _i8.dummyValue<String?>(
          this,
          Invocation.getter(#chatUserId),
        ),
      ) as String?);

  @override
  String? get chatDisplayName => (super.noSuchMethod(
        Invocation.getter(#chatDisplayName),
        returnValue: _i8.dummyValue<String?>(
          this,
          Invocation.getter(#chatDisplayName),
        ),
      ) as String?);
  @override
  _i5.Future<void> updateNebulaApiConfig(
    String? baseUrl,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNebulaApiConfig,
          [
            baseUrl,
            apiKey,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateKeepLoggedIn(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #updateKeepLoggedIn,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isUserLoggedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAppDataPath(
    String? newPath, {
    void Function(
      int,
      int,
    )? onProgress,
    bool Function()? shouldCancel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppDataPath,
          [newPath],
          {
            #onProgress: onProgress,
            #shouldCancel: shouldCancel,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateSplashAnimation(bool? enable) => (super.noSuchMethod(
        Invocation.method(
          #updateSplashAnimation,
          [enable],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveChatAuth({
    required String? accessToken,
    required String? userId,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveChatAuth,
          [],
          {
            #accessToken: accessToken,
            #userId: userId,
            #displayName: displayName,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearChatAuth() => (super.noSuchMethod(
        Invocation.method(
          #clearChatAuth,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
